<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-M73JS29" failures="3" tests="4" name="Test" time="9.27" errors="0" timestamp="2023-11-16T19:11:36 IST">
  <testcase classname="api.tests.UserTest1" name="testPostUser" time="4.365">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.UserTest1.testPostUser(UserTest1.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testPostUser -->
  <testcase classname="api.tests.UserTest1" name="testGetUserData" time="1.738">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.UserTest1.testGetUserData(UserTest1.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserData -->
  <testcase classname="api.tests.UserTest1" name="testUpdateUser" time="1.612"/>
  <testcase classname="api.tests.UserTest1" name="testDeleteUser" time="1.174">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.UserTest1.testDeleteUser(UserTest1.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
</testsuite> <!-- Test -->
